dist: xenial
language: node_js
node_js:
  - 12

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn install

script:
  - yarn test

notifications:
  # Slack notification is secured by Travis Encryption - no sensitive data is leaked with this configuration present
  slack:
    on_success: change
    secure: g0QXf2RO3yfDJLg2cawDy7fjQt+/J4YVCC5kdBy+7ITpHBfv/ccCGCzd8TLyFIzrlPNJemPFq0WCMfFKsS9NGn+AplZtV7e+I8w3975sw3cQSHwTRw/oX0qwQ8LdgwtGToAwWnp4eq8OqtYiXhNMRkF7r1q4Utgl1udJLmPyL5ncCr4fa1MaH+WStu2uOsoZQBB7zlF0GNQa40RWO0qAoy9P68F5tqeW+FVhgFjWdkn7yISGhle0hQMSE10NTt1FwgEDILTmSGMQZsB5UCrlVsQh7EnAS/5FdjIBMhrlRxuwmhViMEvIG2wK3Wzu08vYymDb0OCgm8dvmgNsi6Z65I/erAkUxXVpa5Pn51OK19Pp30zNNY7OzGa/XlBqnUcCYsuZuRNJ9PbP5CIwNB+q8XQqf4Tb2TWkSUSKlyKZcMez2NsHDhXiXcKCpZStnPmDZZot2RgRYnEl48mXCAExrlGuDcOpcLTA7vxW6j0OJK2MzP9qblzmvWFFDXFPjCaHL2s9yIeU4xvQNSSe4TSmWrdRskcvytXEW65hyHCQh0yoSB2yG+CZ01B+FrcsUBuzGIlztmprqBZpjpxPnXRF2cv97cqXxaRirccN41fuI8zXiJj9NXxWO697IDDBGvUu/WmOhHu4mq5au9p8axhCXU//K+0n4NLw9qtAic1PneA=
